credentials:
  usernames:
    lovebyte:
      email: loveenymarufu@gmail.com
      logged_in: False # Will be managed automatically
      name: Loveness Enesia Marufu
      password: 'password123' # Will be hashed automatically
cookie:
  expiry_days: 30
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
  - marufu.loveness@azubiafrica.org
users: